name: Azure ML CI CD

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Azure credentials for Python
      run: |
        AZ_CREDS_B64=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | base64 -w 0)
        echo "AZURE_CREDENTIALS_BASE64=$AZ_CREDS_B64" >> $GITHUB_ENV

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - run: pip install azure-ai-ml azure-identity scikit-learn

    - name: Train Model
      run: python train.py

    - name: Debug Azure environment
      run: |
        echo "AZURE_CLIENT_ID=$AZURE_CLIENT_ID"
        echo "AZURE_TENANT_ID=$AZURE_TENANT_ID"
        echo "AZURE_SUBSCRIPTION_ID=$AZURE_SUBSCRIPTION_ID"

    - name: Deploy Model
      run: python deploy.py

